markdown: redcarpet
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 5
paginate_path: page/:num
encoding: "utf-8"
future: true
lsi: false
safe: true

redcarpet:
    extensions:
        - with_toc_data
        - hard_wrap
        - no_intra_emphasis
        - tables
        - fenced_code_blocks
        - autolink

blog:
    name: meixiang Blog # 博客名称
    description: 分享是一种快乐 # 博客描述
    title: MeiXiang的博客 # 网页标题
    url: meixiang.github.io # 博客地址
author:
    name: Meix # 作者名称
    email: 285645608@qq.com # 邮箱地址
    github: https://github.com/meix # GitHub地址
    logo: /res/img/psb.jpg # logo地址

